%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 720
distortion_parameters:
  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
projection_parameters:
  fx: 908.025390625
  fy: 908.173583984375
  cx: 655.0074462890625
  cy: 381.9485778808594
